<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>FloatingClockOverlay</RootNamespace>
    <AssemblyName>FloatingClockOverlay</AssemblyName>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64</Platforms>
    <Company>Yousa Bin Sadeque</Company>
    <Product>Floating Clock Overlay</Product>
    <Copyright>Copyright © 2026 Yousa Bin Sadeque</Copyright>
    <Version>1.0.0</Version>
  </PropertyGroup>

</Project>
